name: Django Docker Build and AWS ECR Push

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Build Docker Image
        run: |
          docker compose build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: eu-central-1
          role-to-assume: arn:aws:iam::598479110370:role/github

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'false'

      - name: Tag Docker Image
        run: |
          docker tag djangosample-web:latest 598479110370.dkr.ecr.eu-central-1.amazonaws.com/audiosystemS:latest

      - name: Push Docker Image to AWS ECR
        run: |
          docker push 598479110370.dkr.ecr.eu-central-1.amazonaws.com/django:latest
