name: Django Docker Build and AWS ECR Push

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker Image
        run: |
          docker compose build -t django_test:latest .

      - name: AWS ECR Login
        run: |
          aws ecr get-login-password --region eu-central-1 | docker login --username pulumi --password o!S8u5$E 598479110370.dkr.ecr.eu-central-1.amazonaws.com
          

      - name: Tag Docker Image
        run: |
          docker tag django_test:latest 598479110370.dkr.ecr.eu-central-1.amazonaws.com/django_test:latest

      - name: Push Docker Image to AWS ECR
        run: |
          docker push 598479110370.dkr.ecr.eu-central-1.amazonaws.com/django_test:latest
